# Generated by Django 4.0.1 on 2022-02-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='status',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='tasks.Task'),
        ),
    ]
