# Generated by Django 4.0.1 on 2022-02-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskhistory_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
